### ISSUE TITLE
gclToCPU Not working anymore?

### ISSUE THREAD

**Issue by ryu777mtg** [ScreepsMods/screepsmod-admin-utils#16]
I am using the following:
Launcher: screeps-launcher_v1.10.0_windows_amd64.exe
Screeps: Version 4.2.3
Mod: screepsmod-admin-utils version 1.20.3

As stated the option for gclToCPU that can be enabled via the config.yml is no longer working.
I think that it may be broken to the newer version of screeps.

I have the settings set in my config.yml near the bottom of the config.

**Comment by ags131** [comment]
Can you post a copy of the config here? (with any sensitive info like steamKey removed)

**Comment by ryu777mtg** [comment]
Sure here it is:

steamKey: Removed
mods: # Recommended mods
- screepsmod-auth
- screepsmod-admin-utils
- screepsmod-mongo  # You must install and start `mongodb` and `redis` before this mod will work
- screepsmod-dynamicmarket
bots:
  simplebot: screepsbot-zeswarm
serverConfig: # This section requires screepsmod-admin-utils to work
  welcomeText:  |
    <h1 style="text-align: center;">My Private Server</h1>
  shardName: 'pserver1'
  constants: # Used to override screeps constants
    UPGRADE_POWER: 10
    POWER_CREEP_SPAWN_COOLDOWN: 3600000 # 1 Hour
    POWER_CREEP_DELETE_COOLDOWN: 3600000
  tickRate: 200 #5 Tick/Sec
  statsToken: ...splusToken...
  gclToCPU: true
  maxCPU: 100
  baseCPU: 20
  stepCPU: 10

It's pretty much the generic copy

**Comment by ryu777mtg** [comment]
I found the issue it has nothing to do with this mod or the launcher. Apparently when I was launching the Screeps from Steam to connect to the server the Steam mods were being activated on the Client. Weird so I unsubscribed from them all and everything is fine now.

Issue can now be closed.
