### ISSUE TITLE
Add disclaimer about lowercased whitelist

### ISSUE THREAD

**Issue by netthier** [ScreepsMods/screepsmod-admin-utils#22]
After spending way too much troubleshooting this, a disclaimer stating that the whitelist must contain lowercased versions of usernames should be added. 
The source converts all usernames to lowercase before comparing them with the whitelist, meaning that non-lowercase usernames in it are always ignored.

**Comment by ags131** [comment]
Rather than a disclaimer, might be better to just patch the code to be case-insensitive. I'm looking into updating some things anyway, I'll add this to the list :)

**Comment by netthier** [comment]
Ah, I assumed there was a reason for lowercasing the nicknames.
However, wouldnt case-insensitivity allow unauthorized users to log in by creating an account with a differently cased name ("whitelisted_name" vs "wHiTeLiStEd_NaMe")?
Not sure how screeps handles that.

**Comment by ags131** [comment]
The server uses `usernameLower` for the name checks during registration and during login, so is case-insenstive anyway. 
See: https://github.com/screeps/backend-local/blob/master/lib/game/api/register.js#L36

**Comment by netthier** [comment]
Ah, I see. Yeah, making the whitelist case-insensitive is probably the best option then.
