### ISSUE TITLE
Where exectly dose the config file go

### ISSUE THREAD

**Issue by NameVergessen** [ScreepsMods/screepsmod-admin-utils#5]
I can't find the config.yml could you add a description where to find the config in an screeps folder?
I love the possibilitys your mod gives my home server.

**Comment by ags131** [comment]
The config.yml just goes in the same folder as the server files

**Comment by NameVergessen** [comment]
Thank you. GPLtoCPU works just fine now. The welome screen dosn't but it isn't a priority either.
Thank you again for your fast reply.
